version: '1'
services:
  odoo_base:
  image: $ODOO_IMAGE:$ODOO_VERSION
  external_links:
    - aeroo-docs:aeroo
  ports:
    - "8069:8069"
    - "8072:8072"
  volumes:
    - ./data/custom-addons:/opt/odoo/custom-addons
    - odoo_data:/var/lib/odoo/
  env_file:
    - .env